### ISSUE TITLE
Finding better patterns for false positive avoiding.

### ISSUE THREAD

**Issue by antoniovazquezblanco** [wireghoul/graudit#10]
I'm using Graudit with various source codes for testing purposes. I found problems with false positives but I'm not sure how should I improve the databases so I could fix some issues.

The following code is part of a52dec:
```
static inline ao_instance_t * ao_open (ao_open_t * open)
{
    return open ();
}
```

With the `open\s*\(` pattern, declaration of `ao_open` is detected as vulnerable when it clearly isn't. Furthermore the call to `open` inside this function is also not vulnerable but again it is a false positive.

For the first problem I think we should check for for an exact open instead for open preceded by anything. Particular cases such as `something=open(...` should be taken into account.

For the second a minimal check for the correct amount of parameters could work.

What do you think?

**Comment by antoniovazquezblanco** [comment]
I've had to use graudit and this was an issue. As a temporal solution I've used the following patterns:
```
open\s*\([]a-zA-Z0-9&_\[* ]+,[]a-zA-Z0-9&_\[* ]+)			#int open(const char *pathname, int flags);
open\s*\([]a-zA-Z0-9&_\[* ]+,[]a-zA-Z0-9&_\[* ]+,[]a-zA-Z0-9&_\[* ]+)	#int open(const char *pathname, int flags, mode_t mode);
```
There's an issue with multiple line matching because C allows the use of the following code which does not match:
```
static inline ao_instance_t * ao_open (ao_open_t * open,
testing testing)
```
This example patterns should be modified to allow line breaks which implies modifying the call to grep.

**Comment by wireghoul** [comment]
graudit will never do multi line matching, if you need that you should use a soution that supports AST or another form of lexical parsing as opposed to keyword matching.

The rules are a little noisy, some of that could be locked down by duplicating the rules to allow for parsing tokens that mark boundaries. It would have to be duplicate to support open at the start of a line, inside an eval, indented, etc. An example would be to turn open into ^open, [\t\s;{etc]open, etc. Then repeat this for all the rules. It is something I've considered, but I don't have any real issue with the current ruleset for my personal use. If you would like to change all these rules and validate them then feel free to make a pull request.
