### ISSUE TITLE
Test fail in master

### ISSUE THREAD

**Issue by antoniovazquezblanco** [wireghoul/graudit#11]
```
* FAIL 1: 1
	whitespace test test `../graudit -c 0 -d ../signatures/php.db whitespace.php | wc -l` -eq 2
*   ok 2: exec test
* failed 1 among 2 test(s)
```

**Comment by wireghoul** [comment]
Added to my todo list

**Comment by tuhaolam** [comment]
Hi, I just run ./configure and then make on Debian 7, something error raises: 'whitespace test test `../graudit -c 0 -d ../signatures/php.db whitespace.php | wc -l` -eq 2', can you give me some advise? Thanks for your time!

**Comment by wireghoul** [comment]
Issue has been resolved, please try again with the latest git code
