### ISSUE TITLE
[Suggestion] various potentially new rules

### ISSUE THREAD

**Issue by bcoles** [wireghoul/graudit#18]
Maybe some rules of use in here:

https://littlemaninmyhead.wordpress.com/2019/08/04/dont-underestimate-grep-based-code-scanning/

Rule list is at the end.

**Comment by wireghoul** [comment]
Cheers mate, I'll adapt them when I have some time

**Comment by wireghoul** [comment]
Some of them made it into the upcoming 2.3 release. Thanks
