### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by JStyle21** [wireghoul/graudit#22]
Hi,

What is the expected result from a scan? the matched phrases and their location?
Is it possible to get a report of sorts or a vulnerability count?
What's in the default database? because as far as i've seen if i don't choose the right language defaults yields zero results
Are the regular expressions used in the tool borrowed from other tools or made from scratch?

**Comment by wireghoul** [comment]
1. Code smells, file, line and code with surrounding lines for context

2. No, the tool does not analyse the code to determine if the match is a vulnerability or a false positive, this tool is written for humans who are auditing/analysing code, it is not an automated tool. 2a. The reports from flawfinder, etc is largely what made me write my own tool that only gives code context. If you can't tell what bug class the highlighting is pointing out, then this tool may not be the right one for you.

3. Open the file and see. The best results are gained when you write/tune your own rulesets for the bug classes you're hunting for or coding convention of the code base you're reviewing.

4. Both.

**Comment by JStyle21** [comment]
1. So the red part is the match?, what about the lines without red coloring?
2. If i implement it, would you add it to the project?

**Comment by wireghoul** [comment]
1. Depends, but I assume you mean the lines surrounding the red line, they are the # of lines of context, look at the line numbers, it should become clear.

2. No, this is not a report generating tool and never will be. If you intended to analyze matches to determine if they are vulnerabilities you should be using a tokenizer/lexing/ast solution combined with a recursive query capable backend. This would be a completely different application to what graudit is.

Perhaps one of the solutions listed on https://project-awesome.org/mre/awesome-static-analysis would suit your needs/usecase better than graudit.

**Comment by JStyle21** [comment]
Thanks!
I will look at that list and the suggested solutions, i have gone through many tools and lists already and all of them use a match system without reports (at least the free tier) so i guess i will be building my own.
