### ISSUE TITLE
Matching filename via glob

### ISSUE THREAD

**Issue by paolodm** [wireghoul/graudit#23]
graudit produces a LOT of matches. A lot of it are false positives in files I would not be interested in looking in.

It would be absolutely helpful to include / exclude files based on globbing. 

For example:

```
graudit -I './src/service/**/*.js'
graudit -X '**/node_modules/**'
```

**Comment by wireghoul** [comment]
graudit is just a shell script wrapping around unix tools, so this is a no. Unless you can use some fancy features in your shell and grep versions.
Alternately you can do some shell magic like `find <opts> -exec graudit {} \;`

As for the false positives, graudit is only as good as the database you use. I would recommend that you don't scan entire projects using a whole language database, but rather use a subset of rules for specific bug classes to reduce the noise. You can further improve noise to signal by writing custom rules completely.

I show some of the custom rules I use in this presentation: https://www.youtube.com/watch?v=hpYjjj1UAXs, maybe that will help.
