### ISSUE TITLE
greap for "echo" v/s graudit; we can see graudit does not report all usage of echo

### ISSUE THREAD

**Issue by srakshit007** [wireghoul/graudit#26]
DC-C02TK34GGTDY:cr samirkumar.rakshit$ grep -i "echo" *.*
index.php:          <span class="text text-danger"><b><?php echo $error; ?></b></span>
index.php:    <h1>Hi <?php echo h($user); ?>,</h1>
index.php:          <li><a href="/files/<?php echo h($user); ?>/<?php echo h($file); ?>"><?php echo h($file); ?> </a></li>
index.php:      <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data">
login.php:          <span class="text text-danger"><b><?php echo $error; ?></b></span>
register.php:          <span class="text text-danger"><b><?php echo $error; ?></b></span>
DC-C02TK34GGTDY:cr samirkumar.rakshit$ 
DC-C02TK34GGTDY:cr samirkumar.rakshit$ 
DC-C02TK34GGTDY:cr samirkumar.rakshit$ 
DC-C02TK34GGTDY:cr samirkumar.rakshit$ ../../graudit/graudit -A .
===========================================================
                                      .___ __  __   
          _________________  __ __  __| _/|__|/  |_ 
         / ___\_` __ \__  \ |  |  \/ __ | | \\_  __\
        / /_/  >  | \// __ \|  |  / /_/ | |  ||  |  
        \___  /|__|  (____  /____/\____ | |__||__|  
       /_____/            \/           \/           
              grep rough audit - static analysis tool
                  v2.4 written by @Wireghoul
=================================[justanotherhacker.com]===
./index.php-33-    <h3>Upload (only PDF)</h3>
./index.php:34:      <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data">
./index.php-35-            <input type="file" name="file" id="file">
##############################################
##############################################
./classes/user.php-38-    $sql.= "\"";
./classes/user.php:39:    $result = mysql_query($sql);
./classes/user.php-40-    if ($result) {
##############################################
##############################################
./classes/user.php-53-    $sql.= "\")";
./classes/user.php:54:    $result = mysql_query($sql);
./classes/user.php-55-    if ($result) {
##############################################
##############################################
./classes/user.php-71-    $sql.= "\"))";
./classes/user.php:72:    $result = mysql_query($sql);
./classes/user.php-73-    if ($result) {
Binary file ./.index.php.swp matches

**Comment by wireghoul** [comment]
I'm not sure what the question is here....

**Comment by wireghoul** [comment]
Upon closer reading, it appears you want graudit to analyse a specific property of the code.

As you're not specifying a ruleset to run against the code base you get the default rule set which is pretty minimal and tries to find pretty high probability/value vulnerabilities. You might prefer the output of `graudit -d php .` for a noisier output. You can see which rulesets (databases) you have available by running `graudit -l`.

If you just wanted to look at echo you could do either of the following:
`echo "echo" | graudit -d - .` or
```
echo "echo" >> ~/.graudit/onlyecho.db
graudit -d onlyecho .
```

As most codebases have their own code style you'll get better results by using the latter methods.
