### ISSUE TITLE
Can't start scan of a project folder

### ISSUE THREAD

**Issue by team35mazda** [wireghoul/graudit#38]
![image](https://user-images.githubusercontent.com/47948578/96377157-96812000-1151-11eb-8426-9dd3cf1fc480.png)

**Comment by wireghoul** [comment]
Hello,

It appears you don't have grep installed.

Also, you probably don't want to use `-A` (like 99.99% of the time)

**Comment by wireghoul** [comment]
Sorry, I misread the screenshot initially. It appears that the signature databases (in this case default) are not located somewhere the script can find it. Please see the Databases section of the README file. You can always provide the full path to the database:
`graudit -d /mnt/e/Downloads/graudit/signatures/default.db` , or move the databases to one of the expected directories.
You can verify that graudit can find the signatures by running `graudit -l` which will list all the databases graudit can find.

**Comment by team35mazda** [comment]
Thanks for the solution. It works now.

Maybe having an exception catching specific for this case should help users.
