### ISSUE TITLE
Windows style newline characters can cause issues in Cygwin.

### ISSUE THREAD

**Issue by gogo2464** [wireghoul/graudit#40]
When I did `make install` in cygwin I only got the error `./runtests.sh: line 3: $'\r': command not found`

To fix it I used the command `dos2unix graudit/*; make install`.

Then it works perfectly.

So I suggest to include the command dos2unix in the make for cygwin or to directly avoid windows style newline characters.

**Comment by wireghoul** [comment]
I'm afraid your error report is not making any sense:
 * the graudit file does not have DOS line endings
 * runtest.sh line 3 is an empty line and does not have DOS endings

I don't have cygwin to test as I use WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10). If you can determine the actual cause of the issue (the only thing I can think of is perhaps you're missing the printf binary) I can take another look.

**Comment by gogo2464** [comment]
I found the answer to my issue here: https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile/11617204#11617204 it may be useful for you.

**Comment by wireghoul** [comment]
I'm afraid it is not useful as the file does not contain any carriage return bytes unless you added them somehow:
`cat graudit | od -c | grep '\\r'` and `xxd graudit | grep 0d` both show that there are no \r characters in graudit.
