### ISSUE TITLE
Run Fails?

### ISSUE THREAD

**Issue by DougSteiert** [wireghoul/graudit#41]
I am trying to run a scan on some files, but after I submit the command, it just instantly goes to accepting more input and does not display any errors or results from any scan that might've run, without any indication whatsoever what may have happened. Honestly, the "documentation" for this tool is pretty poor, so trying to find answers and help with this has not been easy.

Note: I have blackened several areas of the image for sensitivity purposes, but the important aspects such as location of DB and commands used are there. I am running this on Windows as that is my native OS from which I work on, and the path to the directory is done using "C:/Users/[user]/path/to/directory" as stated.

![image](https://user-images.githubusercontent.com/4563308/104212949-03275600-53f3-11eb-96dd-cbeae32edc22.png)

**Comment by wireghoul** [comment]
graudit doesn't produce reports, any potentially vulnerable code it identifies gets printed on the screen. If no code is printed it didn't identify anything.
