### ISSUE TITLE
Scan specific filetypes only?

### ISSUE THREAD

**Issue by drwetter** [wireghoul/graudit#44]
Hi,

thanks for the tool first!

Besides manual grepping I am using it currently to spot potential candidates for SQL injections in a LAMP stack. 

What I miss is querying PHP files only, so basically the opposite of '-x' as it finds JS files and throws ugly remarks to stderr for binary files like pictures. Same would probably apply for other languages too.

Cheers, Dirk

**Comment by wireghoul** [comment]
I'll have to test this. In my experience it's limited use as code bases may include files names *.inc, *.class, etc and still contain PHP code. I would typically use find -exec graudit {} \; to achieve a granular scan, but if it performs as promised across different OSes I'll merge it.

**Comment by wireghoul** [comment]
Also images are excluded by default unless you're deliberately scanning them with -A

**Comment by drwetter** [comment]
I added a line for me containing *.js and *JPG which caused some pain before for me. I was not looking into the code first.

Don't know how exactly type GLOB pattern works for ``--exclude`` but maybe it's an idea to add uppsercase extensions for the pictures?


> I'll have to test this. In my experience it's limited use as code bases may include files names *.inc, *.class, etc and still contain PHP code.

If one know what the files are ``--include`` could be an option. But sure, there might be a risk missing something

**Comment by wireghoul** [comment]
I've decided this operation doesn't fit how most users should use graudit so I'm going to close the commit and add your feature as a separate script in the misc directory instead for more advanced users to use.

**Comment by drwetter** [comment]
Amendment: the chaotic code I recently went through had lot's of *.PNG + *JPG files. I ended up adding ``--exclude=*.JPG`` and ``--exclude=*.PNG`` to the list.
