### ISSUE TITLE
PHP mysqli::query

### ISSUE THREAD

**Issue by drwetter** [wireghoul/graudit#45]
Hi,

I was struggling in a project to find OO queries which weren't safe. If I didn't overlook anything, graudit didn't help me much. 
So I ended up using grep myself to identify statements like ``"$db_handle->query($unsafe)"`` (which wasn't easy as either there were too many false positives or negatives, depending on my quick choice of grep patterns).

Any chance for a pattern to catch this unsafe OO queries somehow ?

Cheers, Dirk

**Comment by wireghoul** [comment]
Good suggestion. I'll take a closer look at those rules when I have some time

**Comment by wireghoul** [comment]
Added some OOP fruit rules, but investigating this suggests that the number of libraries that uses it would require the use of custom rules, exclusion list or taint analysis (see misc directory) or a combination of these. I wasn't able to write any generic rules that didn't introduce noise.
