### ISSUE TITLE
WordPress dictionary?

### ISSUE THREAD

**Issue by fawp** [wireghoul/graudit#69]
Hi, first of all thanks for the tool - it looks like it's a very nifty tool. Please excuse the newb question, I am trying to understand if I'm doing something wrong here.

I have a PHP test piece of code, just to see how graudit works. The code is going to be intended for a WordPress site, so I am running
`graudit -d wordpress filename.php`

Initially the tool outputs this
![graudit-error01](https://github.com/wireghoul/graudit/assets/57363830/32769e5e-a39b-4124-bea1-40366499db2d)

My understanding is that $_POST is highlighted red because there is no filtering/escaping applied to it.

So, because I am using the wordpress dictionary I add something like `sanitize_text_field()` to the input, like so

![graudit-error02](https://github.com/wireghoul/graudit/assets/57363830/14f41d26-51f1-4f84-b369-333c27d0b28a)

What I would expect the tool to do now is no longer detect that code snippet as vulnerable as it's been sanitized with a WP function, but it still reports it as such.

Am I getting the wrong end of the stick here?

**Comment by wireghoul** [comment]
The WordPress rules are specifically for auditing WordPress plugins. Things that graudit highlights are things that may require attention, or things that are security issues. It's up to the user to do the analysis. I have about 10 hours of source code auditing videos on YouTube, including a graudit tutorial if you want to see how I use it. Just follow the link in the readme.

**Comment by fawp** [comment]
Ok, thanks wireghoul, will do.
