### ISSUE TITLE
Scan files selectively based on file extensions.

### ISSUE THREAD

**Issue by antoniovazquezblanco** [wireghoul/graudit#7]
It would be nice to have a folder scan method that would select databases based on the file extension.

**Comment by wireghoul** [comment]
You can do that easily enough yourself with find and -exec. I dislike this approach as I find it often misses code or uses the wrong langue (ie .class files are which language). The aux/ directory contains some examples of how you can build on graudit to make it fit your needs.

**Comment by antoniovazquezblanco** [comment]
I'm currently using an script to be able to do what you suggest with the find command without too much effort. I'm trying to systematically scan code so I don't mind having the script although I was thinking this may be an interesting feature.

I will consider this a don't want and I will close the issue.
