### ISSUE TITLE
Why random signatures no specification

### ISSUE THREAD

**Issue by MohamedKarrab** [wireghoul/graudit#73]
Why the tool gives us signatures but doesn't specify the vulnerability/severity? I think that would be much more helpful!

**Comment by wireghoul** [comment]
There are several reasons why this is the case:
1. It’s my personal preference to see the code, not a report
2. The rules are regular expressions, not a code analysis engine
3. Any finding in a report would still require validating it in the code

Between my personal opinions and the technical implementation of graudit, it will always only display the code

**Comment by MohamedKarrab** [comment]
Well I still think you can make it specify the vulnerability name even with a confidence %, or specify a few possible vulns together.
